name: Test reusable workflow

on:
  workflow_call:

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
    - run: | 
        exit 1
  B:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "hello"
        
