on:
  workflow_dispatch

jobs:
  use-reusable:
    uses: ./.github/workflows/reusable.yml

  status-check:
    runs-on: ubuntu-latest
    needs: [use-reusable]
    steps:
      - run: echo "Hello"
    
