on:
  workflow_dispatch:
  pull_request:

jobs:
  use-reusable:
    uses: ./.github/workflows/reusable.yml

  status-check:
    needs: use-reusable
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Print the Needs Context
        run: echo "${{ toJson(needs) }}"
        
