on:
  workflow_dispatch:
  pull_request:

jobs:
  use-reusable:
    uses: ./.github/workflows/reusable.yml

  status-check:
    needs: use-reusable
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
